"""add user_id to categories and expenses

Revision ID: fa911c1083e7
Revises: 
Create Date: 2026-08-17 16:55:59.850026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa911c1083e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1 — Add columns as nullable first
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))

    # Step 2 — Fill existing records with the first user's id
    op.execute("UPDATE categories SET user_id = 1 WHERE user_id IS NULL")
    op.execute("UPDATE expenses SET user_id = 1 WHERE user_id IS NULL")

    # Step 3 — Now make the columns NOT NULL
    op.alter_column('categories', 'user_id', nullable=False)
    op.alter_column('expenses', 'user_id', nullable=False)

    # Step 4 — Add foreign key constraints
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])

    # Step 5 — Remove unique constraint on category name
    op.drop_constraint('categories_name_key', 'categories', type_='unique')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
